## Day2-Data cleaning and preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("day1_ML_output.csv")
df.head()

,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,...,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk (Binary),Blood sugar,CK-MB,Troponin,Heart Attack Risk (Text),Gender,Systolic blood pressure,Diastolic blood pressure
0,0.595506,0.314286,0.047663,0.0,0.0,1.0,0.0,0.0,0.208326,0,...,0.0,0.333333,0,0.227018,0.048229,0.036512,0,Male,0.600000,0.534884
1,0.595506,0.096429,0.047663,1.0,1.0,1.0,1.0,1.0,0.752420,1,...,2.0,0.666667,0,0.227018,0.048229,0.036512,0,Male,0.574194,0.569767
2,0.595506,0.189286,0.047663,0.0,0.0,1.0,0.0,1.0,0.200998,2,...,4.0,1.000000,0,0.227018,0.048229,0.036512,0,Male,0.187097,0.674419
3,0.078652,0.960714,0.071494,1.0,1.0,1.0,1.0,1.0,0.090557,2,...,1.0,0.500000,0,0.227018,0.048229,0.036512,0,Male,0.645161,0.593023
4,0.078652,0.792857,0.071494,1.0,0.0,1.0,1.0,0.0,0.601030,2,...,1.0,0.166667,0,0.227018,0.048229,0.036512,0,Male,0.251613,0.383721

In [2]:
#Handing missing values:-
df.isnull().sum()

Age                                0
Cholesterol                        0
Heart rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Heart Attack Risk (Binary)         0
Blood sugar                        0
CK-MB                              0
Troponin                           0
Heart Attack Risk (Text)           0
Gender                             0
Systolic blood pressure            0
Diastolic blood pressure           0
dtype: int64

In [3]:
df.fillna(df.mean(numeric_only=True))

,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,...,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk (Binary),Blood sugar,CK-MB,Troponin,Heart Attack Risk (Text),Gender,Systolic blood pressure,Diastolic blood pressure
0,0.595506,0.314286,0.047663,0.000000,0.000000,1.000000,0.00000,0.000000,0.208326,0,...,0.000000,0.333333,0,0.227018,0.048229,0.036512,0,Male,0.600000,0.534884
1,0.595506,0.096429,0.047663,1.000000,1.000000,1.000000,1.00000,1.000000,0.752420,1,...,2.000000,0.666667,0,0.227018,0.048229,0.036512,0,Male,0.574194,0.569767
2,0.595506,0.189286,0.047663,0.000000,0.000000,1.000000,0.00000,1.000000,0.200998,2,...,4.000000,1.000000,0,0.227018,0.048229,0.036512,0,Male,0.187097,0.674419
3,0.078652,0.960714,0.071494,1.000000,1.000000,1.000000,1.00000,1.000000,0.090557,2,...,1.000000,0.500000,0,0.227018,0.048229,0.036512,0,Male,0.645161,0.593023
4,0.078652,0.792857,0.071494,1.000000,0.000000,1.000000,1.00000,0.000000,0.601030,2,...,1.000000,0.166667,0,0.227018,0.048229,0.036512,0,Male,0.251613,0.383721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9646,0.404494,0.499780,0.091659,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.081028,0.002029,0.006894,2,0,1.000000,1.000000
9647,0.235955,0.499780,0.049496,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.084980,0.003500,0.000194,1,1,0.445161,0.186047
9648,0.348315,0.499780,0.088909,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.330040,0.009540,0.000194,1,1,0.225806,0.302326
9649,0.370787,0.499780,0.067828,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.197628,0.119858,0.025439,2,1,0.258065,0.453488
9650,0.797753,0.499780,0.084326,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.156126,0.006237,0.005923,2,1,0.322581,0.313953

##### Missing values can break ML models.Filling ensures dataset is complete

In [4]:
#Remove Duplicates:-
df.duplicated().sum()

np.int64(0)

In [5]:
df.drop_duplicates()

,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,...,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk (Binary),Blood sugar,CK-MB,Troponin,Heart Attack Risk (Text),Gender,Systolic blood pressure,Diastolic blood pressure
0,0.595506,0.314286,0.047663,0.000000,0.000000,1.000000,0.00000,0.000000,0.208326,0,...,0.000000,0.333333,0,0.227018,0.048229,0.036512,0,Male,0.600000,0.534884
1,0.595506,0.096429,0.047663,1.000000,1.000000,1.000000,1.00000,1.000000,0.752420,1,...,2.000000,0.666667,0,0.227018,0.048229,0.036512,0,Male,0.574194,0.569767
2,0.595506,0.189286,0.047663,0.000000,0.000000,1.000000,0.00000,1.000000,0.200998,2,...,4.000000,1.000000,0,0.227018,0.048229,0.036512,0,Male,0.187097,0.674419
3,0.078652,0.960714,0.071494,1.000000,1.000000,1.000000,1.00000,1.000000,0.090557,2,...,1.000000,0.500000,0,0.227018,0.048229,0.036512,0,Male,0.645161,0.593023
4,0.078652,0.792857,0.071494,1.000000,0.000000,1.000000,1.00000,0.000000,0.601030,2,...,1.000000,0.166667,0,0.227018,0.048229,0.036512,0,Male,0.251613,0.383721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9646,0.404494,0.499780,0.091659,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.081028,0.002029,0.006894,2,0,1.000000,1.000000
9647,0.235955,0.499780,0.049496,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.084980,0.003500,0.000194,1,1,0.445161,0.186047
9648,0.348315,0.499780,0.088909,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.330040,0.009540,0.000194,1,1,0.225806,0.302326
9649,0.370787,0.499780,0.067828,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.197628,0.119858,0.025439,2,1,0.258065,0.453488
9650,0.797753,0.499780,0.084326,0.652554,0.488749,0.902421,0.50016,0.600192,0.502110,3,...,3.501866,0.504621,0,0.156126,0.006237,0.005923,2,1,0.322581,0.313953

In [6]:
#Fix inconsistant values:-
df.nunique()

Age                                  77
Cholesterol                         282
Heart rate                           87
Diabetes                              3
Family History                        3
Smoking                               3
Obesity                               3
Alcohol Consumption                   3
Exercise Hours Per Week            8764
Diet                                  4
Previous Heart Problems               3
Medication Use                        3
Stress Level                         11
Sedentary Hours Per Day            8764
Income                             8616
BMI                                8764
Triglycerides                       772
Physical Activity Days Per Week       9
Sleep Hours Per Day                   8
Heart Attack Risk (Binary)            2
Blood sugar                         245
CK-MB                               701
Troponin                            353
Heart Attack Risk (Text)              3
Gender                                4
Systolic blood pressure             102
Diastolic blood pressure             66
dtype: int64

##### No:of unique values of each columns.   nunique analysis helped identify the number of distinct values in each column. Some categorical variables showed unexpected extra values, indicating data inconsistency, which needs to be handled during preprocessing.

In [7]:
df['Diet'].unique()
df['Gender'].unique()

array(['Male', 'Female', '1', '0'], dtype=object)

##### Ensure no wrong values like:"Male", "male", "M" (inconsistent)
##### Make data uniform

In [8]:
#Convert datatypes:-
df.dtypes

Age                                float64
Cholesterol                        float64
Heart rate                         float64
Diabetes                           float64
Family History                     float64
Smoking                            float64
Obesity                            float64
Alcohol Consumption                float64
Exercise Hours Per Week            float64
Diet                                 int64
Previous Heart Problems            float64
Medication Use                     float64
Stress Level                       float64
Sedentary Hours Per Day            float64
Income                             float64
BMI                                float64
Triglycerides                      float64
Physical Activity Days Per Week    float64
Sleep Hours Per Day                float64
Heart Attack Risk (Binary)           int64
Blood sugar                        float64
CK-MB                              float64
Troponin                           float64
Heart Attack Risk (Text)             int64
Gender                              object
Systolic blood pressure            float64
Diastolic blood pressure           float64
dtype: object

In [9]:
df['Age'].astype(float)

0       0.595506
1       0.595506
2       0.595506
3       0.078652
4       0.078652
          ...
9646    0.404494
9647    0.235955
9648    0.348315
9649    0.370787
9650    0.797753
Name: Age, Length: 9651, dtype: float64

##### ML models need correct data types.Avoid errors during training.

### Label Encoding

##### converts each category into a unique numerical value(labels).

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Gender']

0       3
1       3
2       3
3       3
4       3
       ..
9646    0
9647    1
9648    1
9649    1
9650    1
Name: Gender, Length: 9651, dtype: int64

##### In this method, each unique category is assigned a numerical value.
#### Example:
##### Male → 1  
##### Female → 0  
#### Purpose:
##### Machine learning models require numerical input.Label Encoding helps transform categorical data into a suitable format.
#### Observation:
##### After applying Label Encoding on the Gender column, the values were converted into integers such as 0, 1.
##### This indicates that the column contains multiple categories beyond just binary values.
#### Limitation:
##### Label Encoding introduces an ordinal relationship between categories, which may not be meaningful.
#### Conclusion:
##### Label Encoding is suitable for binary categorical variables. For columns with multiple categories, One-Hot Encoding is a better approach.

### One-Hot Encoding

##### One-Hot Encoding is a technique used to convert more categorical variables into multiple binary (0/1) columns.
#### One-Hot Encoding:
##### The "Diet" column was originally stored as integer values (0, 1, 2), representing different categories.
#### Conclusion:
##### After encoding, all features in the dataset are numerical and suitable for machine learning models.

### Issues Found:
##### No major missing values were observed in the dataset.
##### The dataset contained mostly numerical values, with some encoded categorical features.
##### No significant duplicate records were found.
##### Most features were already normalized between 0 and 1.
### Cleaning Steps Performed:
##### Checked for missing values and handled them if necessary.
##### Verified and removed duplicate rows.
##### Ensured consistency in feature values.
##### Checked and corrected data types where required.
##### Applied encoding techniques where necessary.
### Encoding:
##### Label Encoding was applied for binary categorical variables.
##### One-Hot Encoding was used for categorical variables with more than two categories.
### Assumptions:
##### The dataset is already preprocessed and scaled.
##### Encoded values correctly represent categorical data.
##### No further scaling is required.
### Conclusion:
##### The dataset is clean, consistent, and ready for machine learning model building.

In [11]:
df.to_csv("day2_ML_output.csv",index=False)